# Generated by Django 5.2 on 2025-05-13 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('emblema', models.ImageField(upload_to='emblemas')),
                ('liga', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='votacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votacao_texto', models.CharField(max_length=100)),
                ('data_pub', models.DateTimeField(verbose_name='data de publicação')),
            ],
        ),
        migrations.CreateModel(
            name='utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('bio', models.TextField(blank=True, max_length=100, null=True)),
                ('userType', models.IntegerField(default=0)),
                ('favClub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bd.clube')),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='data de publicação')),
                ('texto', models.TextField(verbose_name='post')),
                ('upvoteNumber', models.IntegerField(default=0)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.clube')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='data de publicação')),
                ('texto', models.TextField(verbose_name='comentário')),
                ('likenumber', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.post')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao_texto', models.CharField(max_length=100)),
                ('votos', models.IntegerField(default=0)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.votacao')),
            ],
        ),
    ]
