# Generated by Django 5.2 on 2025-05-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
