# Generated by Django 5.2.1 on 2025-05-14 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0002_liga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clube',
            name='emblema',
            field=models.ImageField(upload_to='logos/clubes'),
        ),
        migrations.AlterField(
            model_name='clube',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.liga'),
        ),
        migrations.AlterField(
            model_name='liga',
            name='logo',
            field=models.ImageField(upload_to='logos/ligas'),
        ),
        migrations.AlterField(
            model_name='post',
            name='clube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd.clube'),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='favClub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd.clube'),
        ),
    ]
