# Generated by Django 5.2 on 2025-05-15 22:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0002_alter_utilizador_email_alter_utilizador_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='joinDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='join date'),
        ),
    ]
