# Generated by Django 5.2 on 2025-05-15 22:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0003_utilizador_joindate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='joinDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='joinDate'),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='nome',
            field=models.CharField(default='frontend\\public\\default_avatar.png', max_length=100),
        ),
    ]
