# Generated by Django 5.2 on 2025-05-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0005_alter_utilizador_avatar_alter_utilizador_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='avatar',
            field=models.ImageField(default='frontend\\public\\default_avatar.png', upload_to='avatars'),
        ),
    ]
