# Generated by Django 5.2 on 2025-05-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0006_alter_utilizador_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='avatar',
            field=models.ImageField(default='avatars\\default_avatar.png', upload_to='avatars'),
        ),
    ]
