# Generated by Django 5.2 on 2025-05-16 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0007_alter_utilizador_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
        migrations.AddField(
            model_name='post',
            name='liga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd.liga'),
        ),
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.CharField(default='Título', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=models.TextField(blank=True, null=True, verbose_name='post'),
        ),
    ]
