# Generated by Django 5.2 on 2025-05-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0008_post_imagem_post_liga_post_titulo_alter_post_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.png', upload_to='avatars'),
        ),
    ]
