# Generated by Django 5.2.1 on 2025-05-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0009_alter_utilizador_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
