# Generated by Django 5.2.1 on 2025-05-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0010_alter_post_texto_alter_utilizador_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upvoted_users',
            field=models.ManyToManyField(blank=True, related_name='upvoted_posts', to='bd.utilizador'),
        ),
    ]
