# Generated by Django 5.2 on 2025-05-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0012_alter_comentarios_texto_alter_post_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcao',
            name='utilizador',
            field=models.ManyToManyField(blank=True, related_name='votacoes', to='bd.utilizador'),
        ),
    ]
