# Generated by Django 5.2 on 2025-05-18 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0013_opcao_utilizador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opcao',
            old_name='utilizador',
            new_name='votantes',
        ),
    ]
