# Generated by Django 5.2 on 2025-05-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0014_rename_utilizador_opcao_votantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcao',
            name='votantes',
        ),
        migrations.AddField(
            model_name='votacao',
            name='votantes',
            field=models.ManyToManyField(blank=True, related_name='votacoes', to='bd.utilizador'),
        ),
    ]
